# Actions 이름 github 페이지에서 볼 수 있다.
name: Run Test

# Event Trigger 특정 액션 (Push, Pull_Request)등이 명시한 Branch에서 일어나면 동작을 수행한다.
on:
  push:
    branches: [ dev, feat/* ]

  pull_request:
    branches:
      - dev
      - main

  # 실제 어떤 작업을 실행할지에 대한 명시
jobs:
  build:
    runs-on: [ ubuntu-latest ]

    # 실제 실행 스크립트
    steps:
      # uses는 github actions에서 제공하는 플러그인 실행.(git checkout 실행)
      - name: checkout
        uses: actions/checkout@v4

      # with은 plugin 파라미터. (java 17버전 셋업)
      - name: java setup
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: make executable gradlew
        run: chmod +x ./gradlew

      - name: set environment
        run: |
          echo "SPRING_PROFILES_ACTIVE=test" >> $GITHUB_ENV
          echo "SPRING_DATASOURCE_URL=jdbc:h2:mem:test" >> $GITHUB_ENV
          echo "spring.main.allow-bean-definition-overriding=true" >> $GITHUB_ENV
      
          # run은 사용자 지정 스크립트 실행
      - name: run unittest
        run: |
          ./gradlew clean test -P spring.profiles.active=test